name: Release Binary Package
on:
  push:
    tags:
      - v*

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v2.3.1
      - name: Build release artifact
        run: mkdir -p bazel-bin/ && touch bazel-bin/rules_kotlin_release.tgz
      - name: Create release sha256
        run: shasum -a 256 bazel-bin/rules_kotlin_release.tgz > bazel-bin/rules_kotlin_release.tgz.sha256
      - name: Upload bazel-bin/rules_kotlin_release.tgz
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bazel-bin/rules_kotlin_release.tgz
          asset_name: rules_kotlin_release.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload bazel-bin/rules_kotlin_release.tgz.sha256
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bazel-bin/rules_kotlin_release.tgz.sha256
          asset_name: rules_kotlin_release.tgz.sha256
          tag: ${{ github.ref }}
          overwrite: true

